language: C
dist: trusty
sudo: required
notifications:
  email: false

before_install:
- sudo apt-get install ansible linux-headers-$(uname -r) virtualbox-5.1
- mkdir vm-debian-netvirt
- cd vm-debian-netvirt
- wget https://releases.hashicorp.com/vagrant/2.1.0/vagrant_2.1.0_x86_64.deb
- sudo dpkg -i virtualbox-5.1_5.1.0-108711~Ubuntu~trusty_amd64.deb
- sudo dpkg -i vagrant_2.1.0_x86_64.deb
- wget https://raw.githubusercontent.com/netvirt/netvirt/master/build_farm/netvirt.yml

script:
- 'vagrant init vogtmann/debian-7.5-32'
- 'vagrant up'
- 'ansible-playbook -i 127.0.0.1:2222, --private-key ~/.vagrant.d/insecure_private_key -u vagrant -v ./netvirt.yml'
