language: C
dist: trusty
sudo: required
notifications:
  email: false

before_install:
- sudo apt-get install ansible virtualbox vagrant linux-headers-amd64
- mkdir vm-debian-netvirt
- cd vm-debian-netvirt
- wget https://raw.githubusercontent.com/netvirt/netvirt/master/build_farm/netvirt.yml

script:
- 'vagrant init vogtmann/debian-7.5-32'
- 'vagrant up'
- 'ansible-playbook -i 127.0.0.1:2222, --private-key ~/.vagrant.d/insecure_private_key -u vagrant -v ./netvirt.yml'
