language: C
dist: trusty
sudo: required
notifications:
  email: false

before_install:
- sudo apt-get install ansible 
- mkdir vm-debian-netvirt
- cd vm-debian-netvirt
- wget https://raw.githubusercontent.com/netvirt/netvirt/master/build_farm/netvirt.yml

script:
- 'ansible-playbook -v ./netvirt.yml'
